# Generated by Django 5.2 on 2025-04-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikshagpt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='platform',
            field=models.CharField(default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='platform_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
